CREATE TABLE CAR
(
    id VARCHAR(255) PRIMARY KEY NOT NULL,
    BRAND VARCHAR(255),
    COLOR VARCHAR(255),
    ENGINECAPACITY INT(11),
    TYPE VARCHAR(255),
    VERSION BIGINT(20),
    YEAROFBUILD DATE,
    PRICE INT(11)
);
CREATE TABLE USER
(
    id VARCHAR(255) PRIMARY KEY NOT NULL,
    EMAIL VARCHAR(255),
    NAME VARCHAR(255),
    PASSWORDHASH VARCHAR(255),
    VERSION BIGINT(20)
);
CREATE TABLE Rent
(
    id VARCHAR(255) NOT NULL,
    DATEOFRENT DATE,
    PRICE INT(11),
    VERSION BIGINT(20),
    car_id VARCHAR(255),
    user_id VARCHAR(255),
    CONSTRAINT `PRIMARY` PRIMARY KEY (id, id, id, id),
    CONSTRAINT FK_Rent_id FOREIGN KEY (id) REFERENCES CAR (id),
    CONSTRAINT FK_RENT_car_id FOREIGN KEY (car_id) REFERENCES CAR (id),
    CONSTRAINT FK_RENT_user_id FOREIGN KEY (user_id) REFERENCES USER (id)
);
CREATE INDEX FK_RENT_car_id ON Rent (car_id);
CREATE INDEX FK_RENT_user_id ON Rent (user_id);